u dasobjectstore - "DASObjectStore managed storage daemon" /var/lib/dasobjectstore -
g dasobjectstore - "DASObjectStore managed storage daemon group"
g dasobjectstore-admin - "DASObjectStore authenticated Web administration peer group"
