//! Managed daemon boundary for DASObjectStore.

pub mod api;
pub mod application_token_verifier;
pub mod auth;
pub mod client;
#[cfg(feature = "development-self-signing")]
pub mod development_self_signing;
pub mod runtime;
pub mod server;

pub use api::DaemonIngestHddTransferPhase;
pub use api::{
    decide_remote_easyconnect_upload_admission, discover_profile_capabilities,
    plan_remote_easyconnect_upload_handoff, read_provider_stream_frame,
    remote_easyconnect_object_store_grants_for_actor,
    remote_easyconnect_renew_after_offset_seconds,
    resolve_remote_easyconnect_session_lifetime_seconds, write_provider_stream_frame,
    ApplicationAccessTokenExchangeRequest, ApplicationAccessTokenExchangeResponse,
    AssignLocalUserToLocalGroupRequest, AssignLocalUserToLocalGroupResponse,
    CancelIngestJobRequest, CancelIngestJobResponse, CapacityStatusRequest, CapacityStatusResponse,
    CreateLocalGroupRequest, CreateLocalGroupResponse, CreateObjectStoreRequest,
    CreateObjectStoreResponse, CreateObjectStoreValidationError, DaemonApiErrorResponse,
    DaemonApiRequest, DaemonApiResponse, DaemonApiWarning, DaemonDiskHealthSummary,
    DaemonEndpointBinding, DaemonEndpointBindingReadiness, DaemonEndpointKind,
    DaemonEndpointValidation, DaemonEndpointValidationState, DaemonHealthSummaryRequest,
    DaemonHealthSummaryResponse, DaemonIngestAdaptiveSchedulerInput,
    DaemonIngestAdaptiveSchedulingLimit, DaemonIngestAdaptiveWorkerSchedule,
    DaemonIngestBottleneck, DaemonIngestBoundedBufferPolicy, DaemonIngestBufferPoolPolicySet,
    DaemonIngestCompletionFraction, DaemonIngestConflictAction, DaemonIngestConflictDecision,
    DaemonIngestConflictPolicy, DaemonIngestConflictReason, DaemonIngestControlAction,
    DaemonIngestControlState, DaemonIngestErrorRate, DaemonIngestHddActiveTransfer,
    DaemonIngestHddQueueState, DaemonIngestHddTargetQueue, DaemonIngestObjectSnapshot,
    DaemonIngestPipelinePressure, DaemonIngestPipelineStage, DaemonIngestPlacementSchedulerInput,
    DaemonIngestPressure, DaemonIngestProgressEvent, DaemonIngestProgressFractions,
    DaemonIngestQueueDepths, DaemonIngestResourcePolicy, DaemonIngestSchedulingPolicy,
    DaemonIngestStage, DaemonIngestSummary, DaemonIngestSystemSafetyReserve,
    DaemonIngestSystemTelemetry, DaemonIngestTargetCapacity, DaemonIngestTargetFailureState,
    DaemonIngestTelemetry, DaemonIngestThroughputTelemetry, DaemonIngestThroughputTrend,
    DaemonIngestWorkerActivity, DaemonIngestWorkerCounts, DaemonIngestWorkerTelemetry,
    DaemonIngressLandingMode, DaemonIngressOrigin, DaemonJobAcceptedResponse,
    DaemonJobCancelRequest, DaemonJobCancelResponse, DaemonJobEvent, DaemonJobId, DaemonJobIdError,
    DaemonJobKind, DaemonJobListRequest, DaemonJobListResponse, DaemonJobProgress, DaemonJobState,
    DaemonJobStatusRequest, DaemonJobStatusResponse, DaemonJobSummary, DaemonJobValidationError,
    DaemonLocalAdminAcceptedResponse, DaemonLocalAdminCommand, DaemonLocalAdminValidationError,
    DaemonRequestValidationError, DaemonServiceLifecycleRequest, DaemonServiceLifecycleResponse,
    DaemonServiceOperation, DaemonServiceProvisionRequest, DaemonServiceProvisionResponse,
    DaemonServiceStatusDetail, DaemonServiceStatusRequest, DaemonServiceStatusResponse,
    DaemonSourceReadBackpressureAction, DaemonSourceReadBackpressureDecision,
    DaemonSourceReadBackpressureInput, DaemonSourceReadBackpressurePolicy,
    DaemonSourceReadBackpressureReason, DaemonSourceReadPriority, DaemonSourceToSsdPriorityPolicy,
    DaemonSourceToSsdQueueUsage, DaemonSsdPressure, DiskForceRetireRequest, DiskLockdownRequest,
    DiskLockdownResponse, DiskLockdownValidationError, DiskRetireRequest, DiskRetireResponse,
    DiskRetireValidationError, EndpointInventoryValidationError, IngestControlRequest,
    IngestControlResponse, IngestControlValidationError, IngestJobStatusRequest,
    IngestJobStatusResponse, IngestQueueDrainRequest, IngestQueueDrainResponse,
    IngestQueueDrainValidationError, ObjectBrowserBreadcrumb, ObjectBrowserChecksum,
    ObjectBrowserDelegatedActor, ObjectBrowserFileNode, ObjectBrowserFolderNode,
    ObjectBrowserPageRequest, ObjectBrowserPlacement, ObjectBrowserPlacementLocation,
    ObjectBrowserPlacementState, ObjectBrowserReadinessState, ObjectBrowserRequest,
    ObjectBrowserResponse, ObjectBrowserSort, ObjectDownloadRequest, ObjectDownloadResponse,
    ObjectFolderArchiveEntry, ObjectFolderDownloadRequest, ObjectFolderDownloadResponse,
    ObjectPutRequest, ObjectPutResponse, ObjectPutValidationError,
    ObjectStoreCapabilityDiscoveryRequest, ObjectStoreCapabilityDiscoveryResponse,
    PrepareEnclosureFilesystem, PrepareEnclosureHddDevice, PrepareEnclosureRequest,
    PrepareEnclosureResponse, PrepareEnclosureValidationError, ProfileBindingOperation,
    ProfileBindingRequest, ProfileBindingResponse, ProfileBrowserEntry, ProfileBrowserRequest,
    ProfileBrowserResponse, ProfileDiagnosticsRequest, ProfileDiagnosticsResponse,
    ProfileDiagnosticsState, ProfileInspectionRequest, ProfileInspectionResponse,
    ProfileInspectionRootState, ProfileReadinessRequest, ProfileReadinessResponse,
    ProfileS3DeleteRequest, ProfileS3DeleteResponse, ProfileS3HeadRequest, ProfileS3HeadResponse,
    ProfileS3HealthRequest, ProfileS3HealthResponse, ProfileS3ListRequest, ProfileS3ListResponse,
    ProfileS3VerifyRequest, ProfileS3VerifyResponse, ProviderStreamCancellation,
    ProviderStreamChunkHeader, ProviderStreamCondition, ProviderStreamFrameError,
    ProviderStreamOpenRequest, ProviderStreamRange, ProviderStreamUploadOpenRequest,
    ProviderStreamUploadResponse, ProviderStreamValidationError, ProviderStreamVerificationError,
    ProviderStreamVerifier, RemoteEasyconnectApprovePairingRequest,
    RemoteEasyconnectApprovePairingResponse, RemoteEasyconnectAuthProvider,
    RemoteEasyconnectAwsCliEnvironmentVariable, RemoteEasyconnectCreatePairingRequest,
    RemoteEasyconnectCreatePairingResponse, RemoteEasyconnectDiscoveryRequest,
    RemoteEasyconnectDiscoveryResponse, RemoteEasyconnectExchangePairingRequest,
    RemoteEasyconnectExchangePairingResponse, RemoteEasyconnectObjectStoreAccessPolicy,
    RemoteEasyconnectObjectStoreGrant, RemoteEasyconnectRenewSessionRequest,
    RemoteEasyconnectRenewSessionResponse, RemoteEasyconnectRevokeSessionRequest,
    RemoteEasyconnectRevokeSessionResponse, RemoteEasyconnectSession,
    RemoteEasyconnectSessionCredentials, RemoteEasyconnectSessionPolicy,
    RemoteEasyconnectSessionRenewal, RemoteEasyconnectSubmitAwsCliUploadRequest,
    RemoteEasyconnectSubmitAwsCliUploadResponse, RemoteEasyconnectUploadAdmissionDecision,
    RemoteEasyconnectUploadAdmissionRequest, RemoteEasyconnectUploadBackpressureReason,
    RemoteEasyconnectUploadHandoffFailure, RemoteEasyconnectUploadHandoffMode,
    RemoteEasyconnectUploadHandoffRequest, RemoteEasyconnectUploadHandoffResponse,
    RemoteEasyconnectUploadHandoffState, RemoteEasyconnectUploadProgressTelemetry,
    RemoteEasyconnectUploadSelectionEntry, RemoteEasyconnectValidationError,
    StoreDeduplicateReport, StoreDeduplicateRequest, StoreDeduplicateResponse,
    StoreDeduplicateValidationError, StoreDeleteCommandReport, StoreDeleteRequest,
    StoreDeleteResponse, StoreDeleteValidationError, StoreDrainRequest, StoreDrainResponse,
    StoreDrainValidationError, StoreInventoryItem, StoreInventoryRequest, StoreInventoryResponse,
    StoreRepairReport, StoreRepairRequest, StoreRepairResponse, StoreRepairS3Reconciliation,
    StoreRepairValidationError, StoreVerifyReport, StoreVerifyRequest, StoreVerifyResponse,
    SubmitIngestFilesRequest, SubmitIngestFilesResponse, UpdateObjectStoreIngestPolicyRequest,
    UpdateObjectStoreIngestPolicyResponse, UpsertEndpointInventoryRequest,
    UpsertEndpointInventoryResponse, APPLICATION_ACCESS_TOKEN_EXCHANGE_ROUTE,
    DIRECT_TO_HDD_POLICY_CONFIRMATION, DISK_LOCKDOWN_CONFIRMATION, ENCLOSURE_PREPARE_CONFIRMATION,
    ENDPOINT_RECORD_CONFIRMATION, INGEST_CONTROL_CONFIRMATION, INGEST_QUEUE_DRAIN_CONFIRMATION,
    OBJECT_BROWSER_MAX_PAGE_LIMIT, OBJECT_STORE_CREATE_CONFIRMATION,
    PROFILE_BROWSER_MAX_PAGE_LIMIT, PROFILE_BROWSER_SCHEMA_VERSION, PROFILE_READINESS_ROUTE,
    PROVIDER_STREAM_MAX_CHUNK_BYTES, PROVIDER_STREAM_MAX_HEADER_BYTES,
    PROVIDER_STREAM_SCHEMA_VERSION, REMOTE_EASYCONNECT_DEFAULT_SESSION_LIFETIME_SECONDS,
    REMOTE_EASYCONNECT_DISCOVERY_ROUTE, REMOTE_EASYCONNECT_LOCAL_AGENT_HANDOFF_ROUTE,
    REMOTE_EASYCONNECT_MAX_SESSION_LIFETIME_SECONDS,
    REMOTE_EASYCONNECT_MIN_SESSION_LIFETIME_SECONDS, REMOTE_EASYCONNECT_PAIRINGS_ROUTE,
    REMOTE_EASYCONNECT_PAIRING_APPROVAL_ROUTE_TEMPLATE, REMOTE_EASYCONNECT_PAIRING_EXCHANGE_ROUTE,
    REMOTE_EASYCONNECT_RENEWAL_LEAD_SECONDS, REMOTE_EASYCONNECT_SESSIONS_ROUTE,
    REMOTE_EASYCONNECT_SESSION_RENEW_ROUTE_TEMPLATE, REMOTE_EASYCONNECT_SESSION_ROUTE_TEMPLATE,
    STORE_DEDUPLICATE_CONFIRMATION, STORE_DELETE_CONFIRMATION, STORE_DRAIN_CONFIRMATION,
    STORE_REPAIR_CONFIRMATION,
};
pub use api::{
    PROFILE_S3_HEALTH_ROUTE, PROFILE_S3_MULTIPART_COMPLETE_ROUTE, PROFILE_S3_OBJECTS_ROUTE,
    PROFILE_S3_OBJECT_ROUTE, PROFILE_S3_ROUTE_PREFIX,
};
pub use auth::{
    authorize_store_write, DaemonAuthorizationError, DaemonLocalActor, DaemonStoreAccessPolicy,
};
pub use client::{
    DaemonClient, DaemonClientError, DaemonClientTransport, InProcessDaemonTransport,
    ProviderStreamReceipt, UnixSocketDaemonTransport,
};
pub use runtime::{
    admin_job_registry_path, appliance_sample_set, appliance_telemetry_state_path,
    authoritative_performance_recommendation_path, collect_appliance_session_telemetry,
    collect_linux_cpu_telemetry, collect_linux_disk_capacity_telemetry,
    collect_linux_disk_io_telemetry, collect_linux_memory_telemetry,
    default_endpoint_registry_path, default_profile_binding_registry_path, normalize_key,
    parse_linux_cpu_snapshot, parse_linux_diskstats, plan_reconciliation,
    plan_remote_upload_cancellation_cleanup, provision_garage_store_registry,
    query_object_browser_metadata, read_authoritative_ingest_policy, read_object_browser_metadata,
    read_profile_binding, record_remote_upload_s3_transfer_job,
    run_remote_easyconnect_aws_cli_upload_job,
    run_remote_easyconnect_aws_cli_upload_job_with_capacity_provider,
    run_remote_upload_cancellation_cleanup, upsert_endpoint_inventory_record,
    upsert_profile_binding, validate_appliance_telemetry_cadence, AdminJobRegistry,
    ApplianceCpuTelemetry, ApplianceDiskCapacityTelemetry, ApplianceDiskIoTelemetry,
    ApplianceEnclosureTelemetry, ApplianceHostTelemetryCollector, ApplianceMemoryTelemetry,
    ApplianceSessionTelemetry, ApplianceTelemetryCollectionQuality,
    ApplianceTelemetryCollectorError, ApplianceTelemetryLoop, ApplianceTelemetryLoopConfig,
    ApplianceTelemetryLoopError, ApplianceTelemetryMissingDataMarker,
    ApplianceTelemetryMissingReason, ApplianceTelemetrySample, ApplianceTelemetrySampleSet,
    ApplianceTelemetrySink, ApplianceTelemetrySleeper, ApplianceTelemetrySource,
    AuthoritativeIngestPolicy, AuthoritativePerformancePolicyError, BackendProfileBinding,
    CapacityAdmissionProvider, CapacitySpaceProbe, DaemonRuntimeConfig, DaemonRuntimeConfigError,
    DaemonServiceRuntimeError, DaemonTelemetryRuntimeConfig, EndpointRegistryUpsertSummary,
    FileBackedAdminJobRegistry, FileBackedApplianceTelemetrySink,
    FileBackedCapacityAdmissionProvider, FolderCatalogue, FolderCatalogueBrowserEntry,
    FolderCatalogueBrowserQuery, GarageProvisioningSummary, GarageServiceController,
    GarageServiceRuntimeConfig, GarageStoreRegistryProvisioningSummary, LinuxCpuSnapshot,
    LinuxDiskIoCounters, LinuxHostTelemetrySample, LinuxProcTelemetryCollector,
    ObjectBrowserMetadataEntry, ObjectBrowserMetadataReadError, ObjectBrowserQueryError,
    ReconciliationAction, ReconciliationEntryState, ReconciliationManifest,
    ReconciliationManifestEntry, ReconciliationManifestError, ReconciliationObject,
    ReconciliationPlan, RemoteEasyconnectAwsCliUploadJobRequest, RemoteUploadAdmissionGate,
    RemoteUploadAwsCliByteTransfer, RemoteUploadAwsCliTransferPlan,
    RemoteUploadCancellationCleanupAction, RemoteUploadCancellationCleanupActionReport,
    RemoteUploadCancellationCleanupActionState, RemoteUploadCancellationCleanupError,
    RemoteUploadCancellationCleanupPlan, RemoteUploadCancellationCleanupRequest,
    RemoteUploadCancellationCleanupRunReport, RemoteUploadCancellationCleanupRuntime,
    RemoteUploadCancellationCleanupRuntimeConfig, RemoteUploadCancellationCleanupScope,
    RemoteUploadCancellationCleanupWorker, RemoteUploadCompletionCommit,
    RemoteUploadCompletionCommitError, RemoteUploadCompletionMetadata,
    RemoteUploadCompletionRecord, RemoteUploadMultipartAbortConfig, RemoteUploadProgressTelemetry,
    RemoteUploadQueueDepths, RemoteUploadRuntimeSnapshot, RemoteUploadS3ByteTransfer,
    RemoteUploadS3ByteTransferError, RemoteUploadS3TransferJob, RemoteUploadS3TransferJobOutcome,
    RemoteUploadS3TransferJobSummary, RemoteUploadS3TransferPermit,
    RemoteUploadS3TransferProgressReporter, RemoteUploadS3TransferProgressUpdate,
    RemoteUploadS3TransferRunError, RemoteUploadS3TransferWorker,
    RemoteUploadS3TransferWorkerReport, RemoteUploadS3TransferWorkerRequest, ServiceCommandOutput,
    ServiceCommandRunner, StatvfsCapacitySpaceProbe, SystemServiceCommandRunner,
    ThreadApplianceTelemetrySleeper, ADMIN_JOB_REGISTRY_DIR_NAME, ADMIN_JOB_REGISTRY_FILE_NAME,
    ADMIN_JOB_REGISTRY_SCHEMA, APPLIANCE_TELEMETRY_DIR_NAME,
    APPLIANCE_TELEMETRY_FAST_CADENCE_SECONDS, APPLIANCE_TELEMETRY_FILE_NAME,
    APPLIANCE_TELEMETRY_NORMAL_CADENCE_SECONDS, APPLIANCE_TELEMETRY_SCHEMA_VERSION,
    AUTHORITATIVE_PERFORMANCE_DIR_NAME, AUTHORITATIVE_PERFORMANCE_RECOMMENDATION_FILE_NAME,
    DEFAULT_APPLIANCE_TELEMETRY_HDD_ROOT, DEFAULT_DAEMON_CONFIG_PATH, DEFAULT_DAEMON_GROUP,
    DEFAULT_DAEMON_LOG_DIR, DEFAULT_DAEMON_RUNTIME_DIR, DEFAULT_DAEMON_SERVICE_USER,
    DEFAULT_DAEMON_SOCKET_FILE_NAME, DEFAULT_DAEMON_STATE_DIR, DEFAULT_ENDPOINT_REGISTRY_PATH,
    ENDPOINT_REGISTRY_ENV, ENDPOINT_REGISTRY_SCHEMA, LINUX_DAEMON_CONFIG_PATH,
    LINUX_DAEMON_LOG_DIR, LINUX_DAEMON_RUNTIME_DIR, LINUX_DAEMON_STATE_DIR,
    PERFORMANCE_RECOMMENDATION_SCHEMA, PROFILE_BINDING_REGISTRY_SCHEMA,
    RECONCILIATION_MANIFEST_SCHEMA,
};
pub use server::{
    DaemonApiHandler, DaemonClock, DaemonRequestHandler, DaemonRequestHandlerError,
    DaemonServiceOrchestrator, FixedDaemonClock, SystemDaemonClock, UnixSocketDaemonServer,
    UnixSocketDaemonServerError,
};

/// Returns the daemon crate version.
pub fn version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

#[cfg(test)]
mod tests {
    use super::version;

    #[test]
    fn exposes_package_version() {
        assert_eq!(version(), env!("CARGO_PKG_VERSION"));
    }
}
