#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
VALIDATION_ROOT="${DASOBJECTSTORE_CODEX_VALIDATION_ROOT:-${HOME:?HOME is required}/.dasobjectstore-codex-validation}"
APPROVED_ROOT="${HOME:?HOME is required}/.dasobjectstore-codex-validation"
MODE="${1:-inspect}"

case "$VALIDATION_ROOT" in
    "$APPROVED_ROOT"|"$APPROVED_ROOT"/*) ;;
    *) printf 'error: validation root must remain beneath %s\n' "$APPROVED_ROOT" >&2; exit 1 ;;
esac

case "$MODE" in
    inspect|load|validate) ;;
    *) printf 'usage: %s <inspect|load|validate> [evidence.json]\n' "$0" >&2; exit 2 ;;
esac

if [ "$MODE" = validate ]; then
    exec python3 "$SCRIPT_DIR/epic-c-appliance.py" validate "${2:?evidence path required}"
fi

EVIDENCE_DIR="$VALIDATION_ROOT/deployment-evidence"
mkdir -p "$EVIDENCE_DIR"
chmod 700 "$EVIDENCE_DIR"
COMMIT="$(git -C "$REPO_DIR" rev-parse HEAD)"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
REPORT="$EVIDENCE_DIR/epic-c-appliance-$MODE-$COMMIT-$STAMP.json"

if [ "$MODE" = inspect ]; then
    INSPECT_ARGS=(
        inspect
        --repo "$REPO_DIR"
        --output "$REPORT"
        --base-url "${DASOBJECTSTORE_ACCEPTANCE_BASE_URL:-https://127.0.0.1:8448/products/dasobjectstore}"
    )
    if [ -n "${DASOBJECTSTORE_ACCEPTANCE_CA_FILE:-}" ]; then
        INSPECT_ARGS+=(--cafile "$DASOBJECTSTORE_ACCEPTANCE_CA_FILE")
    fi
    python3 "$SCRIPT_DIR/epic-c-appliance.py" "${INSPECT_ARGS[@]}"
    python3 "$SCRIPT_DIR/epic-c-appliance.py" validate "$REPORT"
    printf 'EPIC C inspect-only evidence: %s\n' "$REPORT"
    exit 0
fi

# Load mode is intentionally much harder to enter than inspection. It may only
# operate on generated CODEX data and never infers operator quiescence.
[ "$(uname -s)" = Linux ] || { printf 'error: load acceptance requires Linux\n' >&2; exit 1; }
[ -z "$(git -C "$REPO_DIR" status --porcelain)" ] || {
    printf 'error: load acceptance requires a clean committed revision\n' >&2
    exit 1
}
[ "${DASOBJECTSTORE_ACCEPTANCE_QUIESCENT:-}" = yes ] || {
    printf 'error: set DASOBJECTSTORE_ACCEPTANCE_QUIESCENT=yes after checking the appliance is idle\n' >&2
    exit 1
}
[ "${DASOBJECTSTORE_ACCEPTANCE_CONFIRM:-}" = "RUN EPIC C CODEX LOAD" ] || {
    printf 'error: exact DASOBJECTSTORE_ACCEPTANCE_CONFIRM is required\n' >&2
    exit 1
}
BYTES="${DASOBJECTSTORE_ACCEPTANCE_GENERATED_BYTES:-1073741824}"
case "$BYTES" in *[!0-9]*|'') printf 'error: generated byte count must be numeric\n' >&2; exit 1;; esac
[ "$BYTES" -gt 0 ] && [ "$BYTES" -lt 1099511627776 ] || {
    printf 'error: generated acceptance data must be greater than zero and below 1 TiB\n' >&2
    exit 1
}
if pgrep -af '[d]asobjectstore ingest files' >/dev/null; then
    printf 'error: another file ingest is active; load acceptance requires a quiescent appliance\n' >&2
    exit 1
fi

[ -n "${DASOBJECTSTORE_ACCEPTANCE_COOKIE_FILE:-}" ] || {
    printf 'error: load acceptance requires DASOBJECTSTORE_ACCEPTANCE_COOKIE_FILE for authenticated dashboard sampling\n' >&2
    exit 1
}
[ -r "$DASOBJECTSTORE_ACCEPTANCE_COOKIE_FILE" ] || {
    printf 'error: dashboard cookie file is not readable\n' >&2
    exit 1
}

LOAD_ARGS=(
    load
    --repo "$REPO_DIR"
    --output "$REPORT"
    --validation-root "$VALIDATION_ROOT"
    --run-id "$STAMP"
    --cookie-file "$DASOBJECTSTORE_ACCEPTANCE_COOKIE_FILE"
    --generated-bytes "$BYTES"
    --base-url "${DASOBJECTSTORE_ACCEPTANCE_BASE_URL:-https://127.0.0.1:8448/products/dasobjectstore}"
)
if [ -n "${DASOBJECTSTORE_ACCEPTANCE_CA_FILE:-}" ]; then
    LOAD_ARGS+=(--cafile "$DASOBJECTSTORE_ACCEPTANCE_CA_FILE")
fi
python3 "$SCRIPT_DIR/epic-c-appliance.py" "${LOAD_ARGS[@]}"
printf 'EPIC C load evidence: %s\n' "$REPORT"
