d /run/dasobjectstore 0750 dasobjectstore dasobjectstore -
d /var/lib/dasobjectstore 0750 dasobjectstore dasobjectstore -
d /var/lib/dasobjectstore/report-rebuild 0750 dasobjectstore dasobjectstore -
d /var/log/dasobjectstore 0750 dasobjectstore dasobjectstore -
d /etc/dasobjectstore 0750 root dasobjectstore -
d /opt/dasobjectstore 0750 dasobjectstore dasobjectstore -
d /opt/dasobjectstore/tls 0750 dasobjectstore dasobjectstore -
z /srv/dasobjectstore 0750 dasobjectstore dasobjectstore -
