d /run/dasobjectstore 0750 dasobjectstore dasobjectstore -
d /var/lib/dasobjectstore 0750 dasobjectstore dasobjectstore -
d /var/log/dasobjectstore 0750 dasobjectstore dasobjectstore -
d /etc/dasobjectstore 0750 root dasobjectstore -
z /srv/dasobjectstore 0750 dasobjectstore dasobjectstore -
