[package]
name = "dasobjectstore-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "dasobjectstore"
path = "src/main.rs"

[[bin]]
name = "dasobjectstore-server"
path = "src/server_main.rs"

[[bin]]
name = "dasobjectstore-s3-gateway"
path = "src/s3_gateway_main.rs"

[dependencies]
axum.workspace = true
axum-server.workspace = true
base64.workspace = true
clap.workspace = true
dasobjectstore-core.workspace = true
dasobjectstore-daemon.workspace = true
dasobjectstore-gui-api.workspace = true
dasobjectstore-metadata.workspace = true
dasobjectstore-mnemosyne.workspace = true
dasobjectstore-object-service.workspace = true
dasobjectstore-platform.workspace = true
dasobjectstore-tui.workspace = true
libc.workspace = true
prosopikon-core = { workspace = true, features = ["sqlite"] }
ratatui.workspace = true
rand_core.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
x509-parser.workspace = true
uuid.workspace = true

[features]
debug-commands = []

[dev-dependencies]
chrono.workspace = true
rusqlite.workspace = true
tower.workspace = true
